
runtime: python37


# If `entrypoint` is not defined in app.yaml, App Engine will look for an app
# called `app` in `main.py`.
entrypoint: gunicorn flask_backend:app


# I don't know why "NODE_ENV" is not set in production ...
env_variables:
  ENVIRONMENT: "production"


instance_class: F1
automatic_scaling:
  min_instances: 0
  max_instances: 5

handlers:
- url: /robots.txt
  static_files: flask_backend/static/robots.txt
  upload: flask_backend/static/robots.txt
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto